config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  devise_for :users

  get '/selector' => 'pages#selector'
  get '/visualiser' => 'pages#visualiser'
  get '/campaign' => 'pages#campaign'
  get '/donations' => 'pages#donations'
  get '/secondamend' => 'pages#secondamend'
  get '/library' => 'pages#library'
  get '/links' => 'pages#links'
  get '/news' => 'pages#news'
  get '/aboutus' => 'pages#aboutus'
  get '/contact' => 'pages#contact'
  get '/pages/display_selection' => 'pages#display_selection'
  post '/users' => 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_and_belongs_to_many :pols
end

app/models/pol.rb
class Pol < ApplicationRecord
    has_and_belongs_to_many :groups
    has_and_belongs_to_many :users
    belongs_to :state, :optional => true
end

app/models/state.rb
class State < ApplicationRecord
    has_many :pols
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
    has_and_belongs_to_many :pols
    validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Uncomment this to force authentication:
  # before_action :authenticate_user!, :reload_route

  def reload_route
    Rails.application.reload_routes!
  end

end

app/controllers/pages_controller.rb
# Gun Law Reform Site
# by Ivor King, 2018
# Licence: CC BY

class PagesController < ApplicationController
  def home
    @user = current_user
    if @user != nil
      @user_check = @user.pols.find_by(id: @user)
    end
  end

  def selector 
  end

  def visualiser
  end

  def campaign
  end

  def secondamend
  end

  def donations
  end

  def library
  end

  def links
  end

  def news
  end

  def aboutus
  end

  def contact
  end

  def display_selection
    
    require 'open-uri'

    @name1 = params[:name1].upcase
    if @name1 == nil
      @name1 = "empty"
    end
    
    @name2 = params[:name2].upcase
    if @name2 == nil
      @name2 = "empty"
    end

    @name_selected = @name1 + " " + @name2
    @user = current_user

    @pol = Pol.find_by(name_first: @name1, name_last: @name2)

    if @pol != nil
      @outputmsg = "Match found in the database!"
      if @user == nil     
        @outputmsg << " However, you'll need to log in or sign up first to track and save your selection."
      else
        @user.pols << @pol
      end
    else
      @outputmsg = "No match found in the database."
    end 

    # Site currently uses scrape from opensecrets.org for funding data, and is limited to the US House of Reps. This will be expanded once the op9ensecrets.org API is in use.

    @base_url = 'https://www.politico.com/interactives/2017/gun-lobbying-spending-in-america-congress/'
    @raw_data = Nokogiri::HTML(open( @base_url ))
    @candidate_list = @raw_data.css('td:nth(1)').map &:text
    @funding_list = @raw_data.css('td:nth(2)').map &:text
    @candidate_list.each_with_index do | value, index |
      if @candidate_list[index].upcase == @name_selected
        @locatormsg = "Match found to gun lobby finance website - US House of Representatives members. Candidate has received US #{@funding_list[index]} from gun lobby groups over the course of their career (from 1990, as at Oct 2017)."
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def landing
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Gun Law Reform</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>

<body>

  <div class="loggy">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>

  <div class="container">
      <div class="sidenav">
          <%= link_to 'Home', root_path %>
          <%= link_to 'Select Politician', selector_path %>
          <%= link_to 'Data Visualiser', visualiser_path %>
          <%= link_to 'Campaign Engine', campaign_path %>
          <%= link_to 'Second Amendment', secondamend_path %>
          <%= link_to 'Donate', donations_path %>
          <%= link_to 'Library', library_path %>
          <%= link_to 'Links', links_path %>
          <%= link_to 'News', news_path %>
          <%= link_to 'About Us', aboutus_path %>
          <%= link_to 'Contact', contact_path %>
      </div>

  <div class="main">

    <h3 class="persistent">Gun Law Reform</h3>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>

</body>

</html>

<!--
TO DO
- add twitter API hashtag scroller to this page
- add/modify body content
->

app/views/pages/aboutus.html.erb
<p>This website supports advocacy for gun law reform to reduce the availability of guns in civilian areas of society.</p>

<p>This site focuses on the following jurisdictions:</p>
<ul>
<li>United States</li>
<li>Canada</li>
<li>Mexico</li>
<li>South Africa</li>
<li>United Kingdom</li>
<li>Australia</li>
</ul>

<p>The aim is to encourage long term gun law and policy reform in these jurisdictions.</p>

<p>This site uses automated campaign, communications and public affairs tools and features to support gun control advocates (across all levels and jurisdictions). The site is powered by a secure database containing details of politicians, funding, US states' gun control status, and lobby groups (in favour or against gun control).</p>

<p>We would welcome your involvement! Get in touch, or join our mailing list.</p>

<p><strong>This site is not aligned to any political party, organisation or institution.</strong></p>

<%#
TO DO
- add social media integration: twitter, fb, add email to mailing list
- link to joining mailing list
%>

app/views/pages/blogs.html.erb
<body>

<h1> blogs coming </h1>


<div class="post">
  <h2>A Post About Ducklings</h2>
  <h3 class="author">Some Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

<div class="post">
  <h2>A Post About Ducklings</h2>
  <h3 class="author">Some Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

<div class="post">
  <h2>A Post About Ducklings</h2>
  <h3 class="author">Some Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

</body>

app/views/pages/campaign.html.erb
<p>This is the campaign engine, to generate political and public awareness of the need for gun law reform.</p>

<%# 
TO DO
- tailored options for the user's state, including boilerplate emails, letters, social media posts
- rallies/protests etc. the user can join in their state
- generate tweets directed at user state politicians that are receiving NRA money
%>

app/views/pages/contact.html.erb
<p>Site contact information.</p>

app/views/pages/display_selection.html.erb
<p><%= @outputmsg %></p>
<p><%= @locatormsg %></p>

app/views/pages/donations.html.erb
<p>On this page you can donate to verified gun law reform lobbying groups.</p>

<%# 
TO DO
- add ability for user to donate directly to gun law reform groups in the US
- groups can be suggested based on the user's state
- donations in multiple currencies including cryptos
%>

app/views/pages/home.html.erb
<% if @current_user.present? && @displayed_msg_flag != true %>
    Welcome back <%= @current_user.email %>
    <% @displayed_msg_flag = true%>
<% end %>

<p>This site has been built to support gun control and law reform efforts in the USA, Canada, Mexico, South Africa, UK and Australia.</p>

<p>Gun control is in the news briefly around the time of mass shootings, but then quickly fades from the media and political agenda. Meanwhile, the cumulative toll from gun violence continues to rise.</p>

<p>This site aims to keep gun control on the media and political agenda over the long term.</p>

<%= image_tag("march_image.jpg", :class => "mainpic") %>

<font color="FF8000"><strong>
<% if @var_selected != nil%>
  <p>The politician you're tracking from the database is: <%= @var_selected %></p>
<%elsif @user_check != nil%>
  <p>The politician you're tracking from the database is: <%= @user_check[:name_first] %> <%= @user_check[:name_last] %> (<%= @user_check[:party] %>)</p>
<% end %>
</strong></font>

app/views/pages/library.html.erb
<p>This page lists research and academic sources on gun policy and law reform.</p>

app/views/pages/links.html.erb
<p>This page includes links to other gun policy reform sites.</p>

<h4>USA</h4>

<h4>Mexico</h4>

<h4>South Africa</h4>

<h4>UK</h4>

<h4>Australia</h4>

app/views/pages/news.html.erb
<body>

<p>Gun law reform news</p>

<div class="post">
  <h3>Bump stock bans</h3>
  <h3 class="author">Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

<div class="post">
  <h3>Enhanced background checks</h3>
  <h3 class="author">Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

<div class="post">
  <h3>Raising minimum ages</h3>
  <h3 class="author">Author</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo eveniet repellat voluptate dolores, nostrum nisi quod consequatur nemo labore distinctio quia eos ullam sunt dolore tempore, vero quibusdam ducimus molestias.</p>
    <p>Laboriosam quia blanditiis, totam molestiae incidunt illo odit itaque commodi, ipsa consectetur vero quibusdam hic quae dolores in. Aliquam accusamus deleniti in ab dolorum error debitis similique aliquid eum voluptate.</p>
  </div>
</div>

</body>

app/views/pages/secondamend.html.erb
<p>This page lists information on the second amendment in the USA - frequently cited as a barrier to meaningful gun law reform.</p>

app/views/pages/selector.html.erb
<p>Enter the name of a US Federal politician (House of Representatives) you would like to track.</p>

<p>You will only be able to track politicians that are in the site database.</p>

<main class="flex">
    <form class="column" method="get" action="/pages/display_selection">
        <p class="formpara">
            <label>First name:</label>
            <input class="boxstyle" type="text" name="name1" placeholder="e.g. Paul"><br />
        </p>
        <p class="formpara">
            <label>Second name:</label>
            <input class="boxstyle" type="text" name="name2" placeholder="e.g. Ryan">
        </p>
        <button>Update tracked politician</button>
    </form>
</main>

app/views/pages/visualiser.html.erb
<p>This is the funding data visualiser and database explorer.</p>

<%# 
TO DO
- obtain campaign finance data using an API
- visualise NRA donations to all politicians for user State
- visualise historical donations data for user's chosen politician
- visually display insights into relationships between money, funding, politicians, laws & gun crime (based on analytics)
- allow the user to perform functions on the site database of politicians, and if not visualising the data, then display in a table
%>

app/views/users/landing.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg.capitalize %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up!" %>
<% end %>

app/views/users/users.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg.capitalize %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, :required => true %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up!" %>
<% end %>